{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "26425bbd-ca40-4114-bf70-268fdc345afd",
   "metadata": {},
   "source": [
    "# VGG19\n",
    "\n",
    "## Get embeddings\n",
    "I just download this model from Keras and inference it following their example"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "99eaa031-79cf-4509-8aca-509317e556f3",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Load images\n",
    "import numpy as np\n",
    "from PIL import Image\n",
    "import os\n",
    "\n",
    "# Training\n",
    "image_folder = \"images/training_imgs\"\n",
    "\n",
    "# Log all sets of images so they are in the same order\n",
    "full_body_images = [os.path.join(image_folder, file) for file in os.listdir(image_folder) if file.endswith(\"fb.png\")]\n",
    "clothing_images = [file[:-6] + \"c.png\" for file in full_body_images]\n",
    "full_body_raw = [file[:-6] + \"fb-unedited.png\" for file in full_body_images]\n",
    "\n",
    "# Break into categories\n",
    "clothing_labels = [file.split(\"/\")[-1].split(\"-\")[0].split(\"_\") for file in clothing_images]\n",
    "clothing_images = [Image.open(file) for file in clothing_images]\n",
    "clothing_labels = [[lab[0], lab[1], lab[2][:-1]] if lab[2].endswith(\"s\") else lab for lab in clothing_labels]\n",
    "\n",
    "full_body_labels = [file.split(\"/\")[-1].split(\"-\")[0].split(\"_\") for file in full_body_images]\n",
    "full_body_images = [Image.open(file) for file in full_body_images]\n",
    "full_body_labels = [[lab[0], lab[1], lab[2][:-1]] if lab[2].endswith(\"s\") else lab for lab in full_body_labels]\n",
    "\n",
    "full_body_raw = [Image.open(file) for file in full_body_raw]\n",
    "\n",
    "# Test\n",
    "image_folder = \"images/example_imgs\"\n",
    "\n",
    "# Break into categories\n",
    "test_clothing_images = [Image.open(os.path.join(image_folder, file)) for file in os.listdir(image_folder)]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "3a1a840a-ccc5-48ba-a437-f8b09909b858",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2024-05-06 16:35:42.822605: I tensorflow/core/util/port.cc:113] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.\n",
      "2024-05-06 16:35:42.868666: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.\n",
      "To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.\n",
      "2024-05-06 16:35:43.606443: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT\n",
      "2024-05-06 16:35:44.453751: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1928] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 920 MB memory:  -> device: 0, name: NVIDIA GeForce RTX 4090, pci bus id: 0000:18:00.0, compute capability: 8.9\n",
      "2024-05-06 16:35:44.454276: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1928] Created device /job:localhost/replica:0/task:0/device:GPU:1 with 22189 MB memory:  -> device: 1, name: NVIDIA GeForce RTX 3090, pci bus id: 0000:af:00.0, compute capability: 8.6\n",
      "WARNING: All log messages before absl::InitializeLog() is called are written to STDERR\n",
      "I0000 00:00:1715027745.495598 1212719 service.cc:145] XLA service 0x7fb7f800a480 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:\n",
      "I0000 00:00:1715027745.495669 1212719 service.cc:153]   StreamExecutor device (0): NVIDIA GeForce RTX 4090, Compute Capability 8.9\n",
      "I0000 00:00:1715027745.495679 1212719 service.cc:153]   StreamExecutor device (1): NVIDIA GeForce RTX 3090, Compute Capability 8.6\n",
      "2024-05-06 16:35:45.526347: I tensorflow/compiler/mlir/tensorflow/utils/dump_mlir_util.cc:268] disabling MLIR crash reproducer, set env var `MLIR_CRASH_REPRODUCER_DIRECTORY` to enable.\n",
      "2024-05-06 16:35:45.673956: I external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:465] Loaded cuDNN version 8907\n",
      "2024-05-06 16:35:45.721793: W external/local_tsl/tsl/framework/bfc_allocator.cc:296] Allocator (GPU_0_bfc) ran out of memory trying to allocate 1.83GiB with freed_by_count=0. The caller indicates that this is not a failure, but this may mean that there could be performance gains if more memory were available.\n",
      "2024-05-06 16:35:45.733084: W tensorflow/core/framework/op_kernel.cc:1839] OP_REQUIRES failed at xla_ops.cc:580 : UNKNOWN: Failed to determine best cudnn convolution algorithm for:\n",
      "%cudnn-conv-bias-activation.48 = (f32[32,64,488,488]{3,2,1,0}, u8[0]{0}) custom-call(f32[32,3,488,488]{3,2,1,0} %transpose.34, f32[64,3,3,3]{3,2,1,0} %transpose.35, f32[64]{0} %arg2.3), window={size=3x3 pad=1_1x1_1}, dim_labels=bf01_oi01->bf01, custom_call_target=\"__cudnn$convBiasActivationForward\", metadata={op_type=\"Conv2D\" op_name=\"vgg19_1/block1_conv1_1/convolution\" source_file=\"/home/ian/miniconda3/envs/tf/lib/python3.10/site-packages/tensorflow/python/framework/ops.py\" source_line=1177}, backend_config={\"operation_queue_id\":\"0\",\"wait_on_operation_queues\":[],\"cudnn_conv_backend_config\":{\"conv_result_scale\":1,\"activation_mode\":\"kRelu\",\"side_input_scale\":0,\"leakyrelu_alpha\":0}}\n",
      "\n",
      "Original error: RESOURCE_EXHAUSTED: Out of memory while trying to allocate 1967652864 bytes.\n",
      "\n",
      "To ignore this failure and try to use a fallback algorithm (which may have suboptimal performance), use XLA_FLAGS=--xla_gpu_strict_conv_algorithm_picker=false.  Please also file a bug for the root cause of failing autotuning.\n",
      "2024-05-06 16:35:45.733126: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: UNKNOWN: Failed to determine best cudnn convolution algorithm for:\n",
      "%cudnn-conv-bias-activation.48 = (f32[32,64,488,488]{3,2,1,0}, u8[0]{0}) custom-call(f32[32,3,488,488]{3,2,1,0} %transpose.34, f32[64,3,3,3]{3,2,1,0} %transpose.35, f32[64]{0} %arg2.3), window={size=3x3 pad=1_1x1_1}, dim_labels=bf01_oi01->bf01, custom_call_target=\"__cudnn$convBiasActivationForward\", metadata={op_type=\"Conv2D\" op_name=\"vgg19_1/block1_conv1_1/convolution\" source_file=\"/home/ian/miniconda3/envs/tf/lib/python3.10/site-packages/tensorflow/python/framework/ops.py\" source_line=1177}, backend_config={\"operation_queue_id\":\"0\",\"wait_on_operation_queues\":[],\"cudnn_conv_backend_config\":{\"conv_result_scale\":1,\"activation_mode\":\"kRelu\",\"side_input_scale\":0,\"leakyrelu_alpha\":0}}\n",
      "\n",
      "Original error: RESOURCE_EXHAUSTED: Out of memory while trying to allocate 1967652864 bytes.\n",
      "\n",
      "To ignore this failure and try to use a fallback algorithm (which may have suboptimal performance), use XLA_FLAGS=--xla_gpu_strict_conv_algorithm_picker=false.  Please also file a bug for the root cause of failing autotuning.\n",
      "\t [[{{node StatefulPartitionedCall}}]]\n"
     ]
    },
    {
     "ename": "UnknownError",
     "evalue": "Graph execution error:\n\nDetected at node StatefulPartitionedCall defined at (most recent call last):\n  File \"/home/ian/miniconda3/envs/tf/lib/python3.10/runpy.py\", line 196, in _run_module_as_main\n\n  File \"/home/ian/miniconda3/envs/tf/lib/python3.10/runpy.py\", line 86, in _run_code\n\n  File \"/home/ian/miniconda3/envs/tf/lib/python3.10/site-packages/ipykernel_launcher.py\", line 18, in <module>\n\n  File \"/home/ian/miniconda3/envs/tf/lib/python3.10/site-packages/traitlets/config/application.py\", line 1075, in launch_instance\n\n  File \"/home/ian/miniconda3/envs/tf/lib/python3.10/site-packages/ipykernel/kernelapp.py\", line 739, in start\n\n  File \"/home/ian/miniconda3/envs/tf/lib/python3.10/site-packages/tornado/platform/asyncio.py\", line 205, in start\n\n  File \"/home/ian/miniconda3/envs/tf/lib/python3.10/asyncio/base_events.py\", line 603, in run_forever\n\n  File \"/home/ian/miniconda3/envs/tf/lib/python3.10/asyncio/base_events.py\", line 1909, in _run_once\n\n  File \"/home/ian/miniconda3/envs/tf/lib/python3.10/asyncio/events.py\", line 80, in _run\n\n  File \"/home/ian/miniconda3/envs/tf/lib/python3.10/site-packages/ipykernel/kernelbase.py\", line 545, in dispatch_queue\n\n  File \"/home/ian/miniconda3/envs/tf/lib/python3.10/site-packages/ipykernel/kernelbase.py\", line 534, in process_one\n\n  File \"/home/ian/miniconda3/envs/tf/lib/python3.10/site-packages/ipykernel/kernelbase.py\", line 437, in dispatch_shell\n\n  File \"/home/ian/miniconda3/envs/tf/lib/python3.10/site-packages/ipykernel/ipkernel.py\", line 362, in execute_request\n\n  File \"/home/ian/miniconda3/envs/tf/lib/python3.10/site-packages/ipykernel/kernelbase.py\", line 778, in execute_request\n\n  File \"/home/ian/miniconda3/envs/tf/lib/python3.10/site-packages/ipykernel/ipkernel.py\", line 449, in do_execute\n\n  File \"/home/ian/miniconda3/envs/tf/lib/python3.10/site-packages/ipykernel/zmqshell.py\", line 549, in run_cell\n\n  File \"/home/ian/miniconda3/envs/tf/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3075, in run_cell\n\n  File \"/home/ian/miniconda3/envs/tf/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3130, in _run_cell\n\n  File \"/home/ian/miniconda3/envs/tf/lib/python3.10/site-packages/IPython/core/async_helpers.py\", line 129, in _pseudo_sync_runner\n\n  File \"/home/ian/miniconda3/envs/tf/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3334, in run_cell_async\n\n  File \"/home/ian/miniconda3/envs/tf/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3517, in run_ast_nodes\n\n  File \"/home/ian/miniconda3/envs/tf/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3577, in run_code\n\n  File \"/tmp/ipykernel_1211962/2021728976.py\", line 21, in <module>\n\n  File \"/home/ian/miniconda3/envs/tf/lib/python3.10/site-packages/keras/src/utils/traceback_utils.py\", line 117, in error_handler\n\n  File \"/home/ian/miniconda3/envs/tf/lib/python3.10/site-packages/keras/src/backend/tensorflow/trainer.py\", line 504, in predict\n\n  File \"/home/ian/miniconda3/envs/tf/lib/python3.10/site-packages/keras/src/backend/tensorflow/trainer.py\", line 204, in one_step_on_data_distributed\n\nFailed to determine best cudnn convolution algorithm for:\n%cudnn-conv-bias-activation.48 = (f32[32,64,488,488]{3,2,1,0}, u8[0]{0}) custom-call(f32[32,3,488,488]{3,2,1,0} %transpose.34, f32[64,3,3,3]{3,2,1,0} %transpose.35, f32[64]{0} %arg2.3), window={size=3x3 pad=1_1x1_1}, dim_labels=bf01_oi01->bf01, custom_call_target=\"__cudnn$convBiasActivationForward\", metadata={op_type=\"Conv2D\" op_name=\"vgg19_1/block1_conv1_1/convolution\" source_file=\"/home/ian/miniconda3/envs/tf/lib/python3.10/site-packages/tensorflow/python/framework/ops.py\" source_line=1177}, backend_config={\"operation_queue_id\":\"0\",\"wait_on_operation_queues\":[],\"cudnn_conv_backend_config\":{\"conv_result_scale\":1,\"activation_mode\":\"kRelu\",\"side_input_scale\":0,\"leakyrelu_alpha\":0}}\n\nOriginal error: RESOURCE_EXHAUSTED: Out of memory while trying to allocate 1967652864 bytes.\n\nTo ignore this failure and try to use a fallback algorithm (which may have suboptimal performance), use XLA_FLAGS=--xla_gpu_strict_conv_algorithm_picker=false.  Please also file a bug for the root cause of failing autotuning.\n\t [[{{node StatefulPartitionedCall}}]] [Op:__inference_one_step_on_data_distributed_641]",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mUnknownError\u001b[0m                              Traceback (most recent call last)",
      "Cell \u001b[0;32mIn[2], line 21\u001b[0m\n\u001b[1;32m     11\u001b[0m ds_test \u001b[38;5;241m=\u001b[39m tf\u001b[38;5;241m.\u001b[39mdata\u001b[38;5;241m.\u001b[39mDataset\u001b[38;5;241m.\u001b[39mfrom_generator(\u001b[38;5;28;01mlambda\u001b[39;00m: sample_generator(test_clothing_images), output_signature\u001b[38;5;241m=\u001b[39mimg_spec)\u001b[38;5;241m.\u001b[39mbatch(\u001b[38;5;241m32\u001b[39m)\n\u001b[1;32m     13\u001b[0m model \u001b[38;5;241m=\u001b[39m tf\u001b[38;5;241m.\u001b[39mkeras\u001b[38;5;241m.\u001b[39mapplications\u001b[38;5;241m.\u001b[39mVGG19(\n\u001b[1;32m     14\u001b[0m     include_top\u001b[38;5;241m=\u001b[39m\u001b[38;5;28;01mFalse\u001b[39;00m,\n\u001b[1;32m     15\u001b[0m     weights\u001b[38;5;241m=\u001b[39m\u001b[38;5;124m'\u001b[39m\u001b[38;5;124mimagenet\u001b[39m\u001b[38;5;124m'\u001b[39m,\n\u001b[0;32m   (...)\u001b[0m\n\u001b[1;32m     18\u001b[0m     pooling\u001b[38;5;241m=\u001b[39m\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mavg\u001b[39m\u001b[38;5;124m\"\u001b[39m\n\u001b[1;32m     19\u001b[0m )\n\u001b[0;32m---> 21\u001b[0m clothing_embed \u001b[38;5;241m=\u001b[39m \u001b[43mmodel\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mpredict\u001b[49m\u001b[43m(\u001b[49m\u001b[43mds_clothing\u001b[49m\u001b[43m)\u001b[49m\n\u001b[1;32m     22\u001b[0m full_body_embed \u001b[38;5;241m=\u001b[39m model\u001b[38;5;241m.\u001b[39mpredict(ds_outfit)\n\u001b[1;32m     23\u001b[0m test_embed \u001b[38;5;241m=\u001b[39m model\u001b[38;5;241m.\u001b[39mpredict(ds_test)\n",
      "File \u001b[0;32m~/miniconda3/envs/tf/lib/python3.10/site-packages/keras/src/utils/traceback_utils.py:122\u001b[0m, in \u001b[0;36mfilter_traceback.<locals>.error_handler\u001b[0;34m(*args, **kwargs)\u001b[0m\n\u001b[1;32m    119\u001b[0m     filtered_tb \u001b[38;5;241m=\u001b[39m _process_traceback_frames(e\u001b[38;5;241m.\u001b[39m__traceback__)\n\u001b[1;32m    120\u001b[0m     \u001b[38;5;66;03m# To get the full stack trace, call:\u001b[39;00m\n\u001b[1;32m    121\u001b[0m     \u001b[38;5;66;03m# `keras.config.disable_traceback_filtering()`\u001b[39;00m\n\u001b[0;32m--> 122\u001b[0m     \u001b[38;5;28;01mraise\u001b[39;00m e\u001b[38;5;241m.\u001b[39mwith_traceback(filtered_tb) \u001b[38;5;28;01mfrom\u001b[39;00m \u001b[38;5;28;01mNone\u001b[39;00m\n\u001b[1;32m    123\u001b[0m \u001b[38;5;28;01mfinally\u001b[39;00m:\n\u001b[1;32m    124\u001b[0m     \u001b[38;5;28;01mdel\u001b[39;00m filtered_tb\n",
      "File \u001b[0;32m~/miniconda3/envs/tf/lib/python3.10/site-packages/tensorflow/python/eager/execute.py:53\u001b[0m, in \u001b[0;36mquick_execute\u001b[0;34m(op_name, num_outputs, inputs, attrs, ctx, name)\u001b[0m\n\u001b[1;32m     51\u001b[0m \u001b[38;5;28;01mtry\u001b[39;00m:\n\u001b[1;32m     52\u001b[0m   ctx\u001b[38;5;241m.\u001b[39mensure_initialized()\n\u001b[0;32m---> 53\u001b[0m   tensors \u001b[38;5;241m=\u001b[39m pywrap_tfe\u001b[38;5;241m.\u001b[39mTFE_Py_Execute(ctx\u001b[38;5;241m.\u001b[39m_handle, device_name, op_name,\n\u001b[1;32m     54\u001b[0m                                       inputs, attrs, num_outputs)\n\u001b[1;32m     55\u001b[0m \u001b[38;5;28;01mexcept\u001b[39;00m core\u001b[38;5;241m.\u001b[39m_NotOkStatusException \u001b[38;5;28;01mas\u001b[39;00m e:\n\u001b[1;32m     56\u001b[0m   \u001b[38;5;28;01mif\u001b[39;00m name \u001b[38;5;129;01mis\u001b[39;00m \u001b[38;5;129;01mnot\u001b[39;00m \u001b[38;5;28;01mNone\u001b[39;00m:\n",
      "\u001b[0;31mUnknownError\u001b[0m: Graph execution error:\n\nDetected at node StatefulPartitionedCall defined at (most recent call last):\n  File \"/home/ian/miniconda3/envs/tf/lib/python3.10/runpy.py\", line 196, in _run_module_as_main\n\n  File \"/home/ian/miniconda3/envs/tf/lib/python3.10/runpy.py\", line 86, in _run_code\n\n  File \"/home/ian/miniconda3/envs/tf/lib/python3.10/site-packages/ipykernel_launcher.py\", line 18, in <module>\n\n  File \"/home/ian/miniconda3/envs/tf/lib/python3.10/site-packages/traitlets/config/application.py\", line 1075, in launch_instance\n\n  File \"/home/ian/miniconda3/envs/tf/lib/python3.10/site-packages/ipykernel/kernelapp.py\", line 739, in start\n\n  File \"/home/ian/miniconda3/envs/tf/lib/python3.10/site-packages/tornado/platform/asyncio.py\", line 205, in start\n\n  File \"/home/ian/miniconda3/envs/tf/lib/python3.10/asyncio/base_events.py\", line 603, in run_forever\n\n  File \"/home/ian/miniconda3/envs/tf/lib/python3.10/asyncio/base_events.py\", line 1909, in _run_once\n\n  File \"/home/ian/miniconda3/envs/tf/lib/python3.10/asyncio/events.py\", line 80, in _run\n\n  File \"/home/ian/miniconda3/envs/tf/lib/python3.10/site-packages/ipykernel/kernelbase.py\", line 545, in dispatch_queue\n\n  File \"/home/ian/miniconda3/envs/tf/lib/python3.10/site-packages/ipykernel/kernelbase.py\", line 534, in process_one\n\n  File \"/home/ian/miniconda3/envs/tf/lib/python3.10/site-packages/ipykernel/kernelbase.py\", line 437, in dispatch_shell\n\n  File \"/home/ian/miniconda3/envs/tf/lib/python3.10/site-packages/ipykernel/ipkernel.py\", line 362, in execute_request\n\n  File \"/home/ian/miniconda3/envs/tf/lib/python3.10/site-packages/ipykernel/kernelbase.py\", line 778, in execute_request\n\n  File \"/home/ian/miniconda3/envs/tf/lib/python3.10/site-packages/ipykernel/ipkernel.py\", line 449, in do_execute\n\n  File \"/home/ian/miniconda3/envs/tf/lib/python3.10/site-packages/ipykernel/zmqshell.py\", line 549, in run_cell\n\n  File \"/home/ian/miniconda3/envs/tf/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3075, in run_cell\n\n  File \"/home/ian/miniconda3/envs/tf/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3130, in _run_cell\n\n  File \"/home/ian/miniconda3/envs/tf/lib/python3.10/site-packages/IPython/core/async_helpers.py\", line 129, in _pseudo_sync_runner\n\n  File \"/home/ian/miniconda3/envs/tf/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3334, in run_cell_async\n\n  File \"/home/ian/miniconda3/envs/tf/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3517, in run_ast_nodes\n\n  File \"/home/ian/miniconda3/envs/tf/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3577, in run_code\n\n  File \"/tmp/ipykernel_1211962/2021728976.py\", line 21, in <module>\n\n  File \"/home/ian/miniconda3/envs/tf/lib/python3.10/site-packages/keras/src/utils/traceback_utils.py\", line 117, in error_handler\n\n  File \"/home/ian/miniconda3/envs/tf/lib/python3.10/site-packages/keras/src/backend/tensorflow/trainer.py\", line 504, in predict\n\n  File \"/home/ian/miniconda3/envs/tf/lib/python3.10/site-packages/keras/src/backend/tensorflow/trainer.py\", line 204, in one_step_on_data_distributed\n\nFailed to determine best cudnn convolution algorithm for:\n%cudnn-conv-bias-activation.48 = (f32[32,64,488,488]{3,2,1,0}, u8[0]{0}) custom-call(f32[32,3,488,488]{3,2,1,0} %transpose.34, f32[64,3,3,3]{3,2,1,0} %transpose.35, f32[64]{0} %arg2.3), window={size=3x3 pad=1_1x1_1}, dim_labels=bf01_oi01->bf01, custom_call_target=\"__cudnn$convBiasActivationForward\", metadata={op_type=\"Conv2D\" op_name=\"vgg19_1/block1_conv1_1/convolution\" source_file=\"/home/ian/miniconda3/envs/tf/lib/python3.10/site-packages/tensorflow/python/framework/ops.py\" source_line=1177}, backend_config={\"operation_queue_id\":\"0\",\"wait_on_operation_queues\":[],\"cudnn_conv_backend_config\":{\"conv_result_scale\":1,\"activation_mode\":\"kRelu\",\"side_input_scale\":0,\"leakyrelu_alpha\":0}}\n\nOriginal error: RESOURCE_EXHAUSTED: Out of memory while trying to allocate 1967652864 bytes.\n\nTo ignore this failure and try to use a fallback algorithm (which may have suboptimal performance), use XLA_FLAGS=--xla_gpu_strict_conv_algorithm_picker=false.  Please also file a bug for the root cause of failing autotuning.\n\t [[{{node StatefulPartitionedCall}}]] [Op:__inference_one_step_on_data_distributed_641]"
     ]
    }
   ],
   "source": [
    "# Create embeddings\n",
    "import tensorflow as tf\n",
    "\n",
    "def sample_generator(dataset):\n",
    "    for sample in dataset:\n",
    "        yield tf.keras.applications.vgg19.preprocess_input(np.array(sample))\n",
    "\n",
    "img_spec = tf.TensorSpec((488, 488, 3), float)\n",
    "ds_clothing = tf.data.Dataset.from_generator(lambda: sample_generator(clothing_images), output_signature=img_spec).batch(32)\n",
    "ds_outfit = tf.data.Dataset.from_generator(lambda: sample_generator(full_body_images), output_signature=img_spec).batch(32)\n",
    "ds_test = tf.data.Dataset.from_generator(lambda: sample_generator(test_clothing_images), output_signature=img_spec).batch(32)\n",
    "\n",
    "model = tf.keras.applications.VGG19(\n",
    "    include_top=False,\n",
    "    weights='imagenet',\n",
    "    input_tensor=None,\n",
    "    input_shape=(488, 488, 3),\n",
    "    pooling=\"avg\"\n",
    ")\n",
    "\n",
    "clothing_embed = model.predict(ds_clothing)\n",
    "full_body_embed = model.predict(ds_outfit)\n",
    "test_embed = model.predict(ds_test)"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "5fedb948-8bf0-432c-9b72-39d3966576d9",
   "metadata": {},
   "source": [
    "## Visualize model embeddings"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "0bc78640-9ec2-4c9f-85d9-8d5856dfc067",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Load images\n",
    "import numpy as np\n",
    "from sklearn.decomposition import PCA\n",
    "from sklearn.manifold import TSNE\n",
    "\n",
    "# Break into categories\n",
    "clothing_pca = PCA(n_components=2).fit(clothing_embed)\n",
    "print(clothing_pca.explained_variance_ratio_, sum(clothing_pca.explained_variance_ratio_))\n",
    "clothing_pca = clothing_pca.transform(clothing_embed)\n",
    "clothing_tsne = TSNE().fit_transform(clothing_embed)\n",
    "\n",
    "full_body_pca = PCA(n_components=2).fit(full_body_embed)\n",
    "print(full_body_pca.explained_variance_ratio_, sum(full_body_pca.explained_variance_ratio_))\n",
    "full_body_pca = full_body_pca.transform(full_body_embed)\n",
    "full_body_tsne = TSNE().fit_transform(full_body_embed)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "4d47da06-d576-439f-bfa9-1912d9114de0",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Plot gendered items\n",
    "import matplotlib.pyplot as plt\n",
    "\n",
    "plt.style.use(\"dark_background\")\n",
    "plt.figure(figsize=[5.6, 9.6])\n",
    "for gender in [\"mens\", \"womens\"]:\n",
    "    plt.scatter(\n",
    "        clothing_pca[[i for i in range(len(clothing_pca)) if clothing_labels[i][1] == gender]][:, 0],\n",
    "        clothing_pca[[i for i in range(len(clothing_pca)) if clothing_labels[i][1] == gender]][:, 1],\n",
    "        label=gender\n",
    "    )\n",
    "\n",
    "plt.title(\"VGG19 Embeddings of Clothing by Gender (PCA)\")\n",
    "plt.tight_layout()\n",
    "plt.legend()\n",
    "plt.show()\n",
    "\n",
    "plt.style.use(\"dark_background\")\n",
    "plt.figure(figsize=[5.6, 9.6])\n",
    "for gender in [\"mens\", \"womens\"]:\n",
    "    plt.scatter(\n",
    "        full_body_pca[[i for i in range(len(full_body_pca)) if full_body_labels[i][1] == gender]][:, 0],\n",
    "        full_body_pca[[i for i in range(len(full_body_pca)) if full_body_labels[i][1] == gender]][:, 1],\n",
    "        label=gender\n",
    "    )\n",
    "\n",
    "plt.title(\"VGG19 Embeddings of Outfit by Gender (PCA)\")\n",
    "plt.tight_layout()\n",
    "plt.legend()\n",
    "plt.show()\n",
    "\n",
    "plt.style.use(\"dark_background\")\n",
    "plt.figure(figsize=[5.6, 9.6])\n",
    "for gender in [\"mens\", \"womens\"]:\n",
    "    plt.scatter(\n",
    "        clothing_tsne[[i for i in range(len(clothing_tsne)) if clothing_labels[i][1] == gender]][:, 0],\n",
    "        clothing_tsne[[i for i in range(len(clothing_tsne)) if clothing_labels[i][1] == gender]][:, 1],\n",
    "        label=gender\n",
    "    )\n",
    "\n",
    "plt.title(\"VGG19 Embeddings of Clothing by Gender (TSNE)\")\n",
    "plt.tight_layout()\n",
    "plt.legend()\n",
    "plt.show()\n",
    "\n",
    "plt.style.use(\"dark_background\")\n",
    "plt.figure(figsize=[5.6, 9.6])\n",
    "for gender in [\"mens\", \"womens\"]:\n",
    "    plt.scatter(\n",
    "        full_body_tsne[[i for i in range(len(full_body_tsne)) if full_body_labels[i][1] == gender]][:, 0],\n",
    "        full_body_tsne[[i for i in range(len(full_body_tsne)) if full_body_labels[i][1] == gender]][:, 1],\n",
    "        label=gender\n",
    "    )\n",
    "\n",
    "plt.title(\"VGG19 Embeddings of Outfit by Gender (TSNE)\")\n",
    "plt.tight_layout()\n",
    "plt.legend()\n",
    "plt.show()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "5c76b74e-4f03-4949-917a-c611cc179cfe",
   "metadata": {
    "scrolled": true
   },
   "outputs": [],
   "source": [
    "# Plot types of items\n",
    "\n",
    "plt.style.use(\"dark_background\")\n",
    "plt.figure(figsize=[5.6, 9.6])\n",
    "for item in [\"shirt\", \"top\", \"sweater\", \"pant\", \"skirt\", \"short\"]:    \n",
    "    plt.scatter(\n",
    "        clothing_pca[[i for i in range(len(clothing_pca)) if clothing_labels[i][2] == item]][:, 0],\n",
    "        clothing_pca[[i for i in range(len(clothing_pca)) if clothing_labels[i][2] == item]][:, 1],\n",
    "        label=item\n",
    "    )\n",
    "    \n",
    "plt.title(\"VGG19 Embeddings of Clothing by Type (PCA)\")\n",
    "plt.tight_layout()\n",
    "plt.legend()\n",
    "plt.show()\n",
    "\n",
    "plt.style.use(\"dark_background\")\n",
    "plt.figure(figsize=[5.6, 9.6])\n",
    "for item in [\"shirt\", \"top\", \"sweater\", \"pant\", \"skirt\", \"short\"]:    \n",
    "    plt.scatter(\n",
    "        full_body_pca[[i for i in range(len(full_body_pca)) if full_body_labels[i][2] == item]][:, 0],\n",
    "        full_body_pca[[i for i in range(len(full_body_pca)) if full_body_labels[i][2] == item]][:, 1],\n",
    "        label=item\n",
    "    )\n",
    "    \n",
    "plt.title(\"VGG19 Embeddings of Outfit by Type (PCA)\")\n",
    "plt.tight_layout()\n",
    "plt.legend()\n",
    "plt.show()\n",
    "\n",
    "plt.style.use(\"dark_background\")\n",
    "plt.figure(figsize=[5.6, 9.6])\n",
    "for item in [\"shirt\", \"top\", \"sweater\", \"pant\", \"skirt\", \"short\"]:        \n",
    "    plt.scatter(\n",
    "        clothing_tsne[[i for i in range(len(clothing_tsne)) if clothing_labels[i][2] == item]][:, 0],\n",
    "        clothing_tsne[[i for i in range(len(clothing_tsne)) if clothing_labels[i][2] == item]][:, 1],\n",
    "        label=item\n",
    "    )\n",
    "    \n",
    "plt.title(\"VGG19 Embeddings of Clothing by Type (TSNE)\")\n",
    "plt.tight_layout()\n",
    "plt.legend()\n",
    "plt.show()\n",
    "\n",
    "plt.style.use(\"dark_background\")\n",
    "plt.figure(figsize=[5.6, 9.6])\n",
    "for item in [\"shirt\", \"top\", \"sweater\", \"pant\", \"skirt\", \"short\"]:    \n",
    "    plt.scatter(\n",
    "        full_body_tsne[[i for i in range(len(full_body_tsne)) if full_body_labels[i][2] == item]][:, 0],\n",
    "        full_body_tsne[[i for i in range(len(full_body_tsne)) if full_body_labels[i][2] == item]][:, 1],\n",
    "        label=item\n",
    "    )\n",
    "    \n",
    "plt.title(\"VGG19 Embeddings of Outfit by Type (TSNE)\")\n",
    "plt.tight_layout()\n",
    "plt.legend()\n",
    "plt.show()"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "89be1d73-51db-4176-8997-c3bb28105142",
   "metadata": {},
   "source": [
    "## Testing embeddings using KNN"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "f4078f4a-0eaf-49f8-9a20-a8633f2af5b2",
   "metadata": {},
   "outputs": [],
   "source": [
    "from sklearn.model_selection import train_test_split\n",
    "\n",
    "y_map = {\"shirt\": 0, \"top\": 0, \"sweater\": 1, \"pant\": 2, \"skirt\": 3, \"short\": 4}\n",
    "y = np.array([y_map[label[2]] for label in clothing_labels])\n",
    "X_train, X_test, y_train, y_test = train_test_split(clothing_embed, y, test_size=0.25)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "a2f8806c-b28c-4ce7-8d50-1a42b13c2fcc",
   "metadata": {},
   "outputs": [],
   "source": [
    "from sklearn.neighbors import KNeighborsClassifier\n",
    "from sklearn.metrics import confusion_matrix\n",
    "\n",
    "knn = KNeighborsClassifier()\n",
    "knn.fit(X_train, y_train)\n",
    "\n",
    "matrix = confusion_matrix(y_test, knn.predict(X_test))\n",
    "acc_per_class = matrix.diagonal()/matrix.sum(axis=1)\n",
    "\n",
    "print(acc_per_class)"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "b280c44d-24ac-42c3-b600-304735c4d67c",
   "metadata": {},
   "source": [
    "## Plot demo outfits"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "0bc27703-8e7b-4888-ba5c-b88f16a94a50",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Refit KNN on all training\n",
    "\n",
    "knn.fit(clothing_embed, y)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "209d7ccb-fd8d-4163-9600-dd0d962e145e",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Generate suggested outfits\n",
    "\n",
    "for i, test_emb in enumerate(test_embed):\n",
    "    print(knn.predict(test_emb))\n",
    "    _, axs = plt.subplots(1, 6)\n",
    "    axs[0].axis(\"off\")\n",
    "    # axs[0].set_title(\"Input Clothing\")\n",
    "    axs[0].imshow(test_clothing_images[i])\n",
    "    # axs[3].set_title(\"Suggested Outfits\")\n",
    "\n",
    "    _, inds = knn.kneighbors(np.reshape(test_emb, (1, -1)))\n",
    "    for j, ind in enumerate(inds[0]):\n",
    "        axs[j + 1].axis(\"off\")\n",
    "        axs[j + 1].imshow(full_body_unedited[ind])\n",
    "\n",
    "    plt.show()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "eabfdb96-aea7-4456-a5ad-058db923309e",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "tf",
   "language": "python",
   "name": "tf"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.14"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
